image: rocker/verse:4.3.0
tasks:
  - name: Install Dependencies
    init: |
      sudo apt-get update && \
      sudo apt-get install -y ffmpeg imagemagick && \
      wget -O /tmp/gifski-1.11.0.zip https://gif.ski/gifski-1.11.0.zip && \
      unzip -d /tmp/gifski-1.11.0 /tmp/gifski-1.11.0.zip && \
      sudo apt install /tmp/gifski-1.11.0/linux/gifski_1.11.0_amd64.deb && \
      Rscript -e "devtools::install_deps()"
    
  - name: Start RStudio Server
    command: |
      echo "R_LIBS_USER=/home/gitpod/libs" >> /home/gitpod/.Renviron && \
      echo "session-default-working-dir=/workspace/corise-r-for-ds" | sudo tee -a /etc/rstudio/rsession.conf && \
      echo "gitpod:gitpod" | sudo chpasswd &&\
      sudo rstudio-server start --server-user gitpod
  
ports:
  - name: RStudio
    description: The RStudio Web Server
    port: 8787
    onOpen: open-preview
